"""user_profile: budget_usd_day

Revision ID: 1b7757da0617
Revises: b4b0f6c3b441
Create Date: 2026-08-11 09:17:01.744686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7757da0617'
down_revision: Union[str, Sequence[str], None] = 'b4b0f6c3b441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('budget_usd_day', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'budget_usd_day')
    # ### end Alembic commands ###
