"""strategies with versions

Revision ID: 2eb90198733d
Revises: 89f9a8ee66d3
Create Date: 2026-08-11 11:49:43.967155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb90198733d'
down_revision: Union[str, Sequence[str], None] = '89f9a8ee66d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('niche_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('angle', sa.Text(), nullable=True),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('pillars', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_created_at'), 'strategies', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategies_niche_id'), 'strategies', ['niche_id'], unique=False)
    op.create_index(op.f('ix_strategies_status'), 'strategies', ['status'], unique=False)
    op.add_column('publications', sa.Column('strategy_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_publications_strategy_id'), 'publications', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_strategy_id'), table_name='publications')
    op.drop_column('publications', 'strategy_id')
    op.drop_index(op.f('ix_strategies_status'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_niche_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_created_at'), table_name='strategies')
    op.drop_table('strategies')
    # ### end Alembic commands ###
