"""publications: queue and retry state

Revision ID: 64e59c73f0d2
Revises: 2eb90198733d
Create Date: 2026-08-11 14:32:07.157546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e59c73f0d2'
down_revision: Union[str, Sequence[str], None] = '2eb90198733d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('publications', sa.Column('next_retry_at', sa.DateTime(), nullable=True))
    op.add_column('publications', sa.Column('attempts', sa.Integer(), nullable=True))
    op.add_column('publications', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('publications', sa.Column('text', sa.Text(), nullable=True))
    op.add_column('publications', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('publications', sa.Column('task_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_publications_next_retry_at'), 'publications', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_publications_scheduled_at'), 'publications', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_publications_task_id'), 'publications', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_task_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_scheduled_at'), table_name='publications')
    op.drop_index(op.f('ix_publications_next_retry_at'), table_name='publications')
    op.drop_column('publications', 'task_id')
    op.drop_column('publications', 'image_url')
    op.drop_column('publications', 'text')
    op.drop_column('publications', 'last_error')
    op.drop_column('publications', 'attempts')
    op.drop_column('publications', 'next_retry_at')
    op.drop_column('publications', 'scheduled_at')
    # ### end Alembic commands ###
