"""research and competitors

Revision ID: 89f9a8ee66d3
Revises: fa8da5078117
Create Date: 2026-08-11 11:23:15.803605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f9a8ee66d3'
down_revision: Union[str, Sequence[str], None] = 'fa8da5078117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('niche_id', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('handle', sa.String(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('avg_engagement', sa.Float(), nullable=True),
    sa.Column('top_posts', sa.JSON(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_checked_at'), 'competitors', ['checked_at'], unique=False)
    op.create_index(op.f('ix_competitors_handle'), 'competitors', ['handle'], unique=False)
    op.create_index(op.f('ix_competitors_niche_id'), 'competitors', ['niche_id'], unique=False)
    op.create_index(op.f('ix_competitors_platform'), 'competitors', ['platform'], unique=False)
    op.create_table('research',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('niche_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_created_at'), 'research', ['created_at'], unique=False)
    op.create_index(op.f('ix_research_kind'), 'research', ['kind'], unique=False)
    op.create_index(op.f('ix_research_niche_id'), 'research', ['niche_id'], unique=False)
    op.create_index(op.f('ix_research_task_id'), 'research', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_task_id'), table_name='research')
    op.drop_index(op.f('ix_research_niche_id'), table_name='research')
    op.drop_index(op.f('ix_research_kind'), table_name='research')
    op.drop_index(op.f('ix_research_created_at'), table_name='research')
    op.drop_table('research')
    op.drop_index(op.f('ix_competitors_platform'), table_name='competitors')
    op.drop_index(op.f('ix_competitors_niche_id'), table_name='competitors')
    op.drop_index(op.f('ix_competitors_handle'), table_name='competitors')
    op.drop_index(op.f('ix_competitors_checked_at'), table_name='competitors')
    op.drop_table('competitors')
    # ### end Alembic commands ###
