"""publications: real metrics

Revision ID: fa8da5078117
Revises: 1b7757da0617
Create Date: 2026-08-11 10:57:08.250133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa8da5078117'
down_revision: Union[str, Sequence[str], None] = '1b7757da0617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('niche_id', sa.String(), nullable=True))
    op.add_column('publications', sa.Column('post_url', sa.String(), nullable=True))
    op.add_column('publications', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('publications', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('publications', sa.Column('comments', sa.Integer(), nullable=True))
    op.add_column('publications', sa.Column('saves', sa.Integer(), nullable=True))
    op.add_column('publications', sa.Column('shares', sa.Integer(), nullable=True))
    op.add_column('publications', sa.Column('reach', sa.Integer(), nullable=True))
    op.add_column('publications', sa.Column('engagement_rate', sa.Float(), nullable=True))
    op.add_column('publications', sa.Column('metrics_updated_at', sa.DateTime(), nullable=True))
    op.add_column('publications', sa.Column('topic', sa.String(), nullable=True))
    op.add_column('publications', sa.Column('hook', sa.Text(), nullable=True))
    op.add_column('publications', sa.Column('content_format', sa.String(), nullable=True))
    op.create_index(op.f('ix_publications_niche_id'), 'publications', ['niche_id'], unique=False)
    op.create_index(op.f('ix_publications_plan_id'), 'publications', ['plan_id'], unique=False)
    op.create_index(op.f('ix_publications_published_at'), 'publications', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_published_at'), table_name='publications')
    op.drop_index(op.f('ix_publications_plan_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_niche_id'), table_name='publications')
    op.drop_column('publications', 'content_format')
    op.drop_column('publications', 'hook')
    op.drop_column('publications', 'topic')
    op.drop_column('publications', 'metrics_updated_at')
    op.drop_column('publications', 'engagement_rate')
    op.drop_column('publications', 'reach')
    op.drop_column('publications', 'shares')
    op.drop_column('publications', 'saves')
    op.drop_column('publications', 'comments')
    op.drop_column('publications', 'likes')
    op.drop_column('publications', 'views')
    op.drop_column('publications', 'post_url')
    op.drop_column('publications', 'niche_id')
    # ### end Alembic commands ###
